---
apiVersion: v1
kind: Secret
metadata:
  name: employers-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/ozimakov-demo-org/employers-app-gitops